#!/usr/bin/env python3
"""Compile the check catalog into AI auditor personas.

Single writer of ai-addon/personas/ (see docs/ai-addon.md). Parses the
PRESTON_META block of every core, verified and accepted check — never
the proposed tier, whose detections are unverified — and emits each
persona in three loadable formats:

  personas/claude/<name>.md              raw system prompt
  personas/ollama/Modelfile.<name>       FROM llama3.1 + SYSTEM wrapper
  personas/openai-compatible/<name>.json system + function-calling tools

Persona axes:
  - posture: preston-strict / preston-balanced / preston-permissive,
    mapped from the catalog's per-CVE variant filenames
  - compliance lens: one persona per frameworks: family with >= 15
    mapped checks (source tags nvd/ghsa/osv/kev are not frameworks)

Stdlib only. Deterministic output: no timestamps, sorted ordering, so
regeneration is diff-clean unless the catalog changed.
"""

import importlib.util
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "ai-addon" / "personas"
# Ingestion source tags (mirror .preston-check/state/*.json) and taxonomy
# labels that appear in frameworks: metadata but are not compliance frameworks.
SOURCE_TAGS = {
    "nvd", "ghsa", "osv", "kev", "abuse_ch", "conference_zdi",
    "github_trending", "mailing_list", "mastodon", "newsletter",
    "partner_feed", "reddit", "rss_feeds", "backlog_salvage",
}
MIN_FAMILY_CHECKS = 15
SEV_RANK = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}

GENERATED_NOTE = (
    "GENERATED by tools/build_personas.py — do not edit by hand; "
    "regenerate after check batches land."
)

POSTURES = {
    "preston-strict": (
        "strict",
        "You run at the STRICT posture: flag on reasonable suspicion. A "
        "pattern that could plausibly be the vulnerability is a finding; "
        "prefer a false positive over a missed exposure.",
    ),
    "preston-balanced": (
        "middle",
        "You run at the BALANCED posture: flag findings supported by the "
        "pattern plus at least one corroborating signal in context; note "
        "borderline hits as WARN rather than FAIL.",
    ),
    "preston-permissive": (
        "permissive",
        "You run at the PERMISSIVE posture: flag only high-confidence "
        "findings where the vulnerable pattern is unambiguous; prefer "
        "silence over noise.",
    ),
}


def scanner_version() -> str:
    m = re.search(
        r'^PRESTON_VERSION="([^"]+)"',
        (REPO / "preston-check.sh").read_text(encoding="utf-8"),
        re.M,
    )
    return m.group(1) if m else "unknown"


def load_server():
    """Load ai-addon/mcp/server.py: shares parse_meta and the TOOLS schemas."""
    spec = importlib.util.spec_from_file_location(
        "preston_mcp", REPO / "ai-addon" / "mcp" / "server.py"
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


SERVER = load_server()
CHECK_DIRS = SERVER.CHECK_DIRS  # tier -> directory (proposed deliberately absent)


def variant_of(path: Path) -> str | None:
    m = re.search(r"-(strict|middle|permissive)\.sh$", path.name)
    return m.group(1) if m else None


def distill(meta: dict) -> str:
    """One-line detection intent from description/rationale metadata."""
    desc = meta.get("description", "")
    if "rationale=" in desc:
        desc = desc.rsplit("rationale=", 1)[1]
    desc = re.sub(r"\s+", " ", desc).strip()
    if len(desc) > 180:
        desc = desc[:180].rsplit(" ", 1)[0] + "…"
    return desc


def collect_checks() -> list[dict]:
    checks = []
    for tier, d in CHECK_DIRS.items():
        if not d.is_dir():
            continue
        for path in sorted(d.glob("*.sh")):
            meta = SERVER.parse_meta(path)
            if not meta or not meta.get("id"):
                continue
            families = set()
            for token in meta.get("frameworks", "").split(","):
                family = token.strip().split(":")[0]
                if (family and family.lower() not in SOURCE_TAGS
                        and not family.upper().startswith("CWE")):
                    families.add(family)
            checks.append(
                {
                    "id": meta["id"],
                    "name": meta.get("name", path.stem),
                    "severity": meta.get("severity", "info").lower(),
                    "cwe": meta.get("cwe", ""),
                    "category": meta.get("category", "uncategorized"),
                    "intent": distill(meta),
                    "tier": tier,
                    "variant": variant_of(path),
                    "families": families,
                    "file": str(path.relative_to(REPO)),
                }
            )
    return checks


def sort_key(c: dict):
    m = re.search(r"(\d+)", c["id"])
    return (SEV_RANK.get(c["severity"], 9), int(m.group(1)) if m else 0, c["id"])


def catalog_section(checks: list[dict]) -> str:
    lines = []
    by_cat: dict[str, list[dict]] = {}
    for c in checks:
        by_cat.setdefault(c["category"], []).append(c)
    for cat in sorted(by_cat):
        lines.append(f"### {cat}")
        for c in sorted(by_cat[cat], key=sort_key):
            tag = c["severity"] + (f", {c['cwe']}" if c["cwe"] else "")
            lines.append(f"- {c['id']} {c['name']} [{tag}]: {c['intent']}")
        lines.append("")
    return "\n".join(lines).rstrip()


def system_prompt(title: str, temperament: str, scope_line: str,
                  checks: list[dict], version: str) -> str:
    return f"""<!-- {GENERATED_NOTE} -->
# {title}

You are Preston, a pre-deployment security auditor. Your knowledge of
what to look for is compiled directly from the Preston-Check catalog
(v{version}, {len(checks)} checks): deterministic security tests
hand-curated and auto-evolved from live threat intelligence. You behave
as those tests behave. {scope_line}

{temperament}

## How you audit

Review the code or repository you are given check by check, and report
in the runner's own vocabulary: PASS, FAIL, WARN or SKIP per check,
ordered by severity (critical, high, medium, low, info). Every FAIL or
WARN must cite concrete evidence as file:line references from the code
actually in front of you. Never fabricate a CVE identifier, a line
number, or a finding you cannot point to; if you are uncertain, report
WARN and say why. Findings that originate from unverified early-warning
sources must be labelled [UNVERIFIED].

If Preston-Check tools are available to you (scan_path, list_checks,
explain_check — via MCP or function calling), treat the scanner as
ground truth: run scan_path first, then apply your judgment to triage
results, explain root causes, and propose minimal fixes. Your role on
top of the scanner is interpretation, not re-detection. Without tools,
audit from the compiled knowledge below and state plainly that findings
are model judgment, not scanner evidence.

End every audit with a scorecard (counts per status) and a short
remediation plan ordered by severity.

## What you look for

{catalog_section(checks)}
"""


def emit(name: str, title: str, prompt: str, tools: list[dict]) -> None:
    (OUT / "claude" / f"{name}.md").write_text(prompt, encoding="utf-8")
    escaped = prompt.replace('"""', r"\"\"\"")
    (OUT / "ollama" / f"Modelfile.{name}").write_text(
        f"# {GENERATED_NOTE}\n"
        "# Swap FROM for any local model tag (e.g. kimi-k2, mistral).\n"
        "FROM llama3.1\n"
        "PARAMETER temperature 0.2\n"
        "PARAMETER num_ctx 49152\n"
        f'SYSTEM """\n{escaped}\n"""\n',
        encoding="utf-8",
    )
    (OUT / "openai-compatible" / f"{name}.json").write_text(
        json.dumps(
            {
                "_generated": GENERATED_NOTE,
                "name": name,
                "description": title,
                "system": prompt,
                "tools": [
                    {
                        "type": "function",
                        "function": {
                            "name": t["name"],
                            "description": t["description"],
                            "parameters": t["inputSchema"],
                        },
                    }
                    for t in tools
                ],
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def main() -> int:
    version = scanner_version()
    checks = collect_checks()
    if not checks:
        print("error: no checks with PRESTON_META found", file=sys.stderr)
        return 1
    tools = SERVER.TOOLS
    for sub in ("claude", "ollama", "openai-compatible"):
        (OUT / sub).mkdir(parents=True, exist_ok=True)

    built = []
    for name, (variant, temperament) in POSTURES.items():
        subset = [c for c in checks if c["variant"] in (None, variant)]
        title = f"{name} — Preston-Check auditor ({variant} posture)"
        emit(name, title, system_prompt(
            title, temperament,
            "You cover the full catalog at this posture.",
            subset, version), tools)
        built.append((name, len(subset)))

    families: dict[str, list[dict]] = {}
    for c in checks:
        for fam in c["families"]:
            families.setdefault(fam, []).append(c)
    skipped = []
    for fam in sorted(families):
        subset = families[fam]
        if len(subset) < MIN_FAMILY_CHECKS:
            skipped.append(f"{fam}({len(subset)})")
            continue
        name = "auditor-" + re.sub(r"[^a-z0-9]+", "-", fam.lower()).strip("-")
        title = f"{name} — Preston-Check {fam} compliance auditor"
        emit(name, title, system_prompt(
            title,
            "You run at the BALANCED posture: flag findings supported by "
            "the pattern plus corroborating context; borderline hits are "
            "WARN.",
            f"You audit through the {fam} compliance lens: only checks "
            f"mapped to {fam} controls are in scope, and findings should "
            f"reference the mapped control IDs.",
            subset, version), tools)
        built.append((name, len(subset)))

    for name, n in built:
        print(f"built {name}: {n} checks")
    if skipped:
        print(f"skipped framework families under {MIN_FAMILY_CHECKS} checks: "
              + ", ".join(skipped))
    print(f"catalog v{version}, {len(checks)} checks parsed, "
          f"{len(built)} personas -> {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
